# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#hero'
    weight: 10
  - name: Aim
    url: '#aim'
    weight: 20
  - name: Task
    url: '#task'
    weight: 30
  - name: Data
    url: '#data'
    weight: 40
  - name: Rules
    url: '#rules'
    weight: 50
  - name: Evaluation
    url: '#evaluation'
    weight: 60
  - name: Team
    url: '#people'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
